FROM ghcr.io/graalvm/native-image-community:25 AS build
WORKDIR /app
COPY mvnw mvnw
COPY .mvn .mvn
COPY pom.xml .
RUN --mount=type=cache,target=/root/.m2 ./mvnw dependency:go-offline -B
COPY src ./src
RUN --mount=type=cache,target=/root/.m2 ./mvnw clean -DskipTests -Pnative native:compile

FROM ubuntu:resolute
WORKDIR /app
COPY --from=build /app/target/oneclick-deployment app
COPY --from=build /app/target/*.so .
ENTRYPOINT ["/app/app"]
