name: oneclick-deployment

volumes:
  postgres:

networks:
  oneclick-deployment:

services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-oneclick-deployment}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_USER=${POSTGRES_USER:-user}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql
    networks:
      - oneclick-deployment

  app:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-oneclick-deployment}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    ports:
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - oneclick-deployment
    depends_on:
      - postgres